---
- name: Prepare secret YAML and deploy to multiple Kubernetes datacenters
  hosts: localhost
  gather_facts: no
  vars_files:
    - "{{ lookup('env', 'PWD') + '/' + config }}"  # Loads config.yml, config variable passed as an argument

  tasks:
    - name: Load config file
      include_vars:
        file: "{{ lookup('env', 'PWD') + '/' + config }}"

    - name: Prepare and encode secrets
      set_fact:
        encoded_secrets: "{{ encoded_secrets | default({}) | combine({item.key: (item.value | string | b64encode)}) }}"
      loop: "{{ secrets | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Generate secret file from config
      set_fact:
        secret_yaml: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ secret_name | default('default') }}
            namespace: {{ namespace | default('default') }}
          type: Opaque
          data:
            {% for key, value in encoded_secrets.items() %}
            {{ key }}: {{ value }}
            {% endfor %}

    - name: Save secret locally
      copy:
        content: "{{ secret_yaml }}"
        dest: "./{{ secret_name }}-{{ enviroment }}.yml"
        mode: '0600'

    - name: Switch Kubernetes context to "{{ context }}"
      command: kubectx "{{ context }}"
      loop: "{{ kubernetes_contexts }}"
      loop_control:
        loop_var: context

    - name: Apply Kubernetes secret in "{{ context }}"
      command: kubectl apply -f "./{{ secret_name }}-{{ enviroment }}.yml"
      register: kubectl_output
      loop: "{{ kubernetes_contexts }}"
      loop_control:
        loop_var: context

    - name: Debug Kubernetes output for "{{ context }}"
      debug:
        var: kubectl_output.stdout
      loop: "{{ kubernetes_contexts }}"
      loop_control:
        loop_var: context
