---
- name: Prepare secret YAML
  hosts: localhost
  gather_facts: no
  vars_files:
    - config.yml
  tasks:
    - name: Prepare and encode secrets
      set_fact:
        encoded_secrets: "{{ encoded_secrets | default({}) | combine({item.key: (item.value | string | b64encode)}) }}"
      loop: "{{ secrets | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
    
    - name: Generate secret file from config
      set_fact:
        secret_yaml: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ secret_name | default('default') }}
            namespace: {{ namespace | default('default') }}
          type: Opaque
          data:
            {% for key, value in encoded_secrets.items() %}
            {{ key }}: {{ value }}
            {% endfor %}
    - name: Secret print
      debug:
        msg: "{{ secret_yaml.split('\n') }}"
    
    - name: Save secret
      copy:
        content: "{{ secret_yaml }}"
        dest: "./{{ secret_name }}-{{ enviroment }}.yaml"
        mode: '0600'
    
    - name: Generated secret file
      debug:
        msg: "Secret file ./{{ secret_name }}-{{ enviroment }}.yaml"
